brain_two/brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('todos/', include("todos.urls")),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url="/todos")),
]

brain_two/todos/urls.py
from django.urls import path

from todos.views import (
    TodoItemCreateView,
    TodoItemUpdateView,
    TodoListCreateView,
    TodoListDeleteView,
    TodoListDetailView,
    TodoListListView,
    TodoListUpdateView,
)


urlpatterns = [
    path("", TodoListListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoListCreateView.as_view(), name="todo_list_create"),
    path(
        "<int:pk>/edit/",
        TodoListUpdateView.as_view(),
        name="todo_list_update",
    ),
    path(
        "<int:pk>/delete/",
        TodoListDeleteView.as_view(),
        name="todo_list_delete",
    ),
    path(
        "items/create/",
        TodoItemCreateView.as_view(),
        name="todo_item_create",
    ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todo_item_update",
    ),
]

brain_two/todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length = 100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length = 100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )
    def __str__(self):
        return self.task

brain_two/todos/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from todos.models import TodoItem, TodoList


class TodoListListView(ListView):
    model = TodoList
    template_name = "todo_lists/list.html"


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todo_lists/detail.html"


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todo_lists/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todo_lists/update.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todo_lists/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todo_items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todo_items/update.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

brain_two/todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todo Lists</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>

brain_two/todos/templates/todo_items/create.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>Create a new item</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit</button>
      </form>
    </div>
  </main>
{% endblock content %}

brain_two/todos/templates/todo_items/update.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>Update item</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit</button>
      </form>
    </div>
  </main>
{% endblock content %}

brain_two/todos/templates/todo_lists/create.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>Update list</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Update</button>
      </form>
    </div>
  </main>
{% endblock content %}

brain_two/todos/templates/todo_lists/delete.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>Are you sure?</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Delete</button>
      </form>
    </div>
  </main>
{% endblock content %}

brain_two/todos/templates/todo_lists/detail.html
{% extends 'base.html' %}
{% block content %}
  <main>
    <div>
      <h1>{{ todolist.name }}</h1>
      <p><a href="{% url 'todo_list_update' todolist.id %}">Edit</a></p>
      <p><a href="{% url 'todo_list_delete' todolist.id %}">Delete</a></p>
      <h2>Tasks</h2>
      <table>
        <thead>
          <tr>
            <th>Task</th>
            <th>Due date</th>
          </tr>
        </thead>
        <tbody>
          {% for item in todolist.items.all %}
            <tr>
              <td>
                <a href="{% url 'todo_item_update' item.id %}">{{ item.task }}</a>
              </td>
              <td>{{ item.due_date|date:"M d, Y" }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
{% endblock content %}

brain_two/todos/templates/todo_lists/list.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div>
      <h1>My lists</h1>
      <p><a href="{% url 'todo_list_create' %}">Create a new list</a></p>
      <p><a href="{% url 'todo_item_create' %}">Create a new item</a></p>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Number of items</th>
          </tr>
        </thead>
        <tbody>
          {% for list in todolist_list %}
            <tr>
              <td>
                <a href="{% url 'todo_list_detail' list.id %}">
                  {{ list.name }}
                </a>
              </td>
              <td>{{ list.items.all|length }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    
  </main>
{% endblock content %}

brain_two/todos/templates/todo_lists/update.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Recipe - Scrumptious</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'list_todos' %}">Home</a>
        </li>
      </ul>
    </nav>
  </header>
  <main class="recipe-form">
    
    <h1>Update List</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        Name:<input type="text">
        <button class="button">Update</button>
      </div>
    </form>

  </main>
</body>

</html>